version: "3.7"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:4.2.9
    restart: always
    ports:
      - 27017:27017
    networks:
      - default

networks:
  default:
    driver: bridge
